with open(r'C:\Users\ASUS\Documents\Default Project\frontend\lib\map_page.dart', 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Find the class closing brace (line 885, index 884)
# Insert all helper methods BEFORE line 885 (index 884)
insert_idx = 884  # 0-indexed, line 885 is index 884

new_methods = [
    '',
    '  // ============================================================',
    '  // Helper methods',
    '  // ============================================================',
    '',
    '  PolylineLayer _buildRouteLayer() {',
    '    if (_segments.isEmpty) {',
    '      return PolylineLayer(polylines: []);',
    '    }',
    '    return PolylineLayer(',
    '      polylines: _segments.map((seg) => Polyline(',
    '        points: seg.points,',
    '        color: seg.color,',
    '        strokeWidth: seg.width,',
    '      )).toList(),',
    '    );',
    '  }',
    '',
    '  MarkerLayer _buildMarkerLayer() {',
    '    if (_markers.isEmpty) {',
    '      return MarkerLayer(markers: []);',
    '    }',
    '    return MarkerLayer(',
    '      markers: _markers.map((m) {',
    '        Widget child;',
    '        switch (m.type) {',
    '          case "start":',
    '            child = const Icon(Icons.location_on, color: Colors.green, size: 40);',
    '            break;',
    '          case "end":',
    '            child = const Icon(Icons.flag, color: Colors.red, size: 40);',
    '            break;',
    '          case "start_select":',
    '            child = const Icon(Icons.my_location, color: Colors.green, size: 36);',
    '            break;',
    '          case "end_select":',
    '            child = const Icon(Icons.location_searching, color: Colors.red, size: 36);',
    '            break;',
    '          case "bus_stop":',
    '            child = Column(',
    '              mainAxisSize: MainAxisSize.min,',
    '              children: [',
    '                const Icon(Icons.directions_bus, color: Colors.orange, size: 30),',
    '                if (m.route.isNotEmpty)',
    '                  Container(',
    '                    padding: const EdgeInsets.symmetric(horizontal: 4, vertical: 1),',
    '                    decoration: BoxDecoration(',
    '                      color: Colors.orange,',
    '                      borderRadius: BorderRadius.circular(8),',
    '                    ),',
    '                    child: Text(',
    '                      m.route,',
    '                      style: const TextStyle(color: Colors.white, fontSize: 10),',
    '                    ),',
    '                  ),',
    '                if (m.label.isNotEmpty)',
    '                  Container(',
    '                    margin: const EdgeInsets.only(top: 2),',
    '                    padding: const EdgeInsets.symmetric(horizontal: 4, vertical: 1),',
    '                    decoration: BoxDecoration(',
    '                      color: Colors.black87,',
    '                      borderRadius: BorderRadius.circular(4),',
    '                    ),',
    '                    child: Text(',
    '                      m.label,',
    '                      style: const TextStyle(color: Colors.white, fontSize: 9),',
    '                    ),',
    '                  ),',
    '              ],',
    '            );',
    '            break;',
    '          default:',
    '            child = const Icon(Icons.place, color: Colors.blue, size: 30);',
    '        }',
    '        return Marker(',
    '          point: m.point,',
    '          width: m.type == "bus_stop" ? 60 : 40,',
    '          height: m.type == "bus_stop" ? 60 : 40,',
    '          child: child,',
    '        );',
    '      }).toList(),',
    '    );',
    '  }',
    '',
    '  IconData _getPlaceIcon(String? type) {',
    '    switch (type) {',
    '      case "building": return Icons.location_city;',
    '      case "amenity": return Icons.place;',
    '      case "tourism": return Icons.attractions;',
    '      case "shop": return Icons.shopping_bag;',
    '      case "leisure": return Icons.park;',
    '      case "historic": return Icons.account_balance;',
    '      default: return Icons.location_on;',
    '    }',
    '  }',
    '',
    '  String _formatAddress(Map<String, dynamic> addr) {',
    '    final parts = <String>[];',
    '    if (addr["road"] != null) parts.add(addr["road"]);',
    '    if (addr["suburb"] != null) parts.add(addr["suburb"]);',
    '    if (addr["city"] != null) parts.add(addr["city"]);',
    '    if (addr["state"] != null) parts.add(addr["state"]);',
    '    return parts.join("\u2009");',
    '  }',
    '',
    '  Widget _buildSliderField(String label, double value, double min, double max, ValueChanged<double> onChanged, {String suffix = ""}) {',
    '    return Column(',
    '      crossAxisAlignment: CrossAxisAlignment.start,',
    '      children: [',
    '        Text("$label: ${value.toStringAsFixed(suffix == "%" ? 0 : 1)}$suffix", style: const TextStyle(fontSize: 12)),',
    '        Slider(',
    '          value: value,',
    '          min: min,',
    '      max: max,',
    '          divisions: (max - min).toInt(),',
    '          label: "${value.toStringAsFixed(suffix == "%" ? 0 : 1)}$suffix",',
    '          onChanged: onChanged,',
    '        ),',
    '      ],',
    '    );',
    '  }',
    '',
    '  Widget _buildInfoRow(String label, String value) {',
    '    return Padding(',
    '      padding: const EdgeInsets.symmetric(vertical: 2),',
    '      child: Row(',
    '        mainAxisAlignment: MainAxisAlignment.spaceBetween,',
    '        children: [',
    '          Text(label, style: const TextStyle(fontSize: 13, color: Colors.grey)),',
    '          Text(value, style: const TextStyle(fontSize: 13, fontWeight: FontWeight.w500)),',
    '        ],',
    '      ),',
    '    );',
    '  }',
    '',
    '  Future<void> _parseIntent(String text) async {',
    '    if (text.trim().isEmpty) return;',
    '',
    '    setState(() {',
    '      _chatMessages.add(_ChatMessage(text: text, isUser: true));',
    '      _isParsingIntent = true;',
    '    });',
    '',
    '    try {',
    '      final response = await http.post(',
    '        Uri.parse("$_apiBase/ai/parse_intent"),',
    '        headers: {"Content-Type": "application/json"},',
    '        body: jsonEncode({"text": text}),',
    '      ).timeout(const Duration(seconds: 10));',
    '',
    '      if (response.statusCode == 200) {',
    '        final data = jsonDecode(response.body);',
    '        setState(() {',
    '          _chatMessages.add(_ChatMessage(',
    '            text: _formatIntentResponse(data),',
    '            isUser: false,',
    '            parsedIntent: data,',
    '          ));',
    '        });',
    '        _applyParsedIntent(data);',
    '      } else {',
    '        setState(() {',
    '          _chatMessages.add(_ChatMessage(',
    '            text: "解析失敗: ${response.statusCode}",',
    '            isUser: false,',
    '          ));',
    '        });',
    '      }',
    '    } catch (e) {',
    '      setState(() {',
    '        _chatMessages.add(_ChatMessage(',
    '          text: "請求失敗: $e",',
    '            isUser: false,',
    '        ));',
    '      });',
    '    } finally {',
    '      setState(() {',
    '        _isParsingIntent = false;',
    '    });',
    '  }',
    '',
    '  void _applyParsedIntent(Map<String, dynamic> data) {',
    '    setState(() {',
    '      if (data["avoid_stairs"] != null) _avoidStairs = data["avoid_stairs"] as bool;',
    '      if (data["max_slope"] != null) _maxSlope = (data["max_slope"] as num).toDouble();',
    '      if (data["max_walk_km"] != null) _maxWalkKm = (data["max_walk_km"] as num).toDouble();',
    '      if (data["prefer_bus"] != null) _preferBus = data["prefer_bus"] as bool;',
    '      if (data["wheelchair"] != null) _wheelchair = data["wheelchair"] as bool;',
    '    });',
    '  }',
    '',
    '  String _formatIntentResponse(Map<String, dynamic> data) {',
    '    final parts = <String>[];',
    '    if ((data["tags"] as List?)?.isNotEmpty == true) parts.add("標籤: ${(data["tags"] as List).join(", ")}");',
    '    if (data["avoid_stairs"] == true) parts.add("避開階梯");',
    '    if (data["max_slope"] != null) parts.add("最大坡度: ${data["max_slope"]}%");',
    '    if (data["max_walk_km"] != null) parts.add("最大步行: ${data["max_walk_km"]}km");',
    '    if (data["prefer_bus"] == true) parts.add("優先公車");',
    '    if (data["wheelchair"] == true) parts.add("無障礙模式");',
    '    if (data["poi_category"] != null) parts.add("POI類別: ${data["poi_category"]}");',
    '    return parts.isEmpty ? "已解析(無特殊偏好)" : parts.join("\\n");',
    '  }',
    '',
    '  Future<void> _searchPlaces(String query, bool isStart) async {',
    '    if (query.length < 2) {',
    '      setState(() {',
    '        if (isStart) {',
    '          _startSuggestions = [];',
    '        } else {',
    '          _endSuggestions = [];',
    '        }',
    '      });',
    '      return;',
    '    }',
    '',
    '    try {',
    '      final response = await http.get(',
    '        Uri.parse("$_apiBase/geocode/search?q=${Uri.encodeComponent(query)}&limit=8"),',
    '        headers: {"Accept": "application/json"},',
    '      ).timeout(const Duration(seconds: 5));',
    '',
    '      if (response.statusCode == 200) {',
    '        final List<dynamic> data = jsonDecode(response.body);',
    '        final results = data.map((e) => _GeocodeResult.fromJson(e)).toList();',
    '        setState(() {',
    '          if (isStart) {',
    '            _startSuggestions = results;',
    '        } else {',
    '          _endSuggestions = results;',
    '        }',
    '        });',
    '      }',
    '    } catch (e) {',
    '      // Ignore search errors',
    '    }',
    '  }',
    '',
    '  void _removeOverlays() {',
    '    // No overlays to remove with new approach',
    '  }',
    '',
    '  void _selectPlace(_GeocodeResult place, bool isStart) {',
    '    _removeOverlays();',
    '    final lat = place.lat;',
    '    final lon = place.lon;',
    '',
    '    setState(() {',
    '      if (isStart) {',
    '        _startNameController.text = place.displayName;',
    '        _startLatController.text = lat.toString();',
    '        _startLonController.text = lon.toString();',
    '        _startSuggestions = [];',
    '      } else {',
    '        _endNameController.text = place.displayName;',
    '        _endLatController.text = lat.toString();',
    '        _endLonController.text = lon.toString();',
    '        _endSuggestions = [];',
    '      }',
    '    });',
    '',
    '    _updateSelectionMarker(isStart, LatLng(lat, lon));',
    '  }',
    '',
    '  void _updateSelectionMarker(bool isStart, LatLng point) {',
    '    setState(() {',
    '      if (isStart) {',
    '        _markers.removeWhere((m) => m.type == "start_select");',
    '        _markers.add(_MapMarker(',
    '          point: point,',
    '          type: "start_select",',
    '          label: "起點",',
    '        ));',
    '      } else {',
    '        _markers.removeWhere((m) => m.type == "end_select");',
    '        _markers.add(_MapMarker(',
    '          point: point,',
    '          type: "end_select",',
    '          label: "終點",',
    '        ));',
    '      }',
    '    });',
    '    WidgetsBinding.instance.addPostFrameCallback((_) {',
    '      _mapController.move(point, _initialZoom);',
    '    });',
    '    if (_startLatController.text.isNotEmpty && _endLatController.text.isNotEmpty) {',
    '      _planRoute();',
    '    }',
    '  }',
    '',
    '  void _onMapTap(LatLng point) {',
    '    if (_isSelectingStart) {',
    '      _selectPlaceFromMap(point, true);',
    '    } else if (_isSelectingEnd) {',
    '      _selectPlaceFromMap(point, false);',
    '    }',
    '  }',
    '',
    '  Future<void> _selectPlaceFromMap(LatLng point, bool isStart) async {',
    '    try {',
    '      final response = await http.get(',
    '        Uri.parse("$_apiBase/geocode/reverse?lat=${point.latitude}&lon=${point.longitude}"),',
    '        headers: {"Accept": "application/json"},',
    '      ).timeout(const Duration(seconds: 5));',
    '',
    '      if (response.statusCode == 200) {',
    '        final data = jsonDecode(response.body);',
    '        final name = data["display_name"] as String? ?? "選取位置";',
    '',
    '        setState(() {',
    '          if (isStart) {',
    '            _startNameController.text = name;',
    '            _startLatController.text = point.latitude.toString();',
    '            _startLonController.text = point.longitude.toString();',
    '          } else {',
    '            _endNameController.text = name;',
    '            _endLatController.text = point.latitude.toString();',
    '            _endLonController.text = point.longitude.toString();',
    '          }',
    '        });',
    '        _updateSelectionMarker(isStart, point);',
    '      }',
    '    } catch (e) {',
    '      setState(() {',
    '        if (isStart) {',
    '          _startLatController.text = point.latitude.toString();',
    '      _startLonController.text = point.longitude.toString();',
    '        } else {',
    '          _endLatController.text = point.latitude.toString();',
    '          _endLonController.text = point.longitude.toString();',
    '        }',
    '      });',
    '      _updateSelectionMarker(isStart, point);',
    '    }',
    '  }',
    '',
    '  void _parseGeojson(Map<String, dynamic> geojson) {',
    '    _routePoints.clear();',
    '    _segments.clear();',
    '    _markers.removeWhere((m) => m.type == "start" || m.type == "end" || m.type == "bus_stop");',
    '',
    '    final features = geojson["features"] as List<dynamic>?;',
    '    if (features == null) return;',
    '',
    '    for (final feature in features) {',
    '      final props = feature["properties"] as Map<String, dynamic>?;',
    '      final geom = feature["geometry"] as Map<String, dynamic>?;',
    '      if (props == null || geom == null) continue;',
    '',
    '      final type = geom["type"] as String?;',
    '      final coords = geom["coordinates"];',
    '',
    '      if (type == "LineString") {',
    '        final mode = props["mode"] as String? ?? "walk";',
    '        final points = <LatLng>[];',
    '        for (final coord in coords) {',
    '          points.add(LatLng((coord[1] as num).toDouble(), (coord[0] as num).toDouble()));',
    '        }',
    '',
    '        if (mode == "bus") {',
    '          _segments.add(_RouteSegment(',
    '            points: points,',
    '            color: Colors.orange,',
    '            width: 5.0,',
    '            isBus: true,',
    '            routeName: props["route"] as String? ?? "",',
    '            distance: (props["distance"] as num?)?.toDouble() ?? 0,',
    '            time: (props["time"] as num?)?.toDouble() ?? 0,',
    '          ));',
    '        } else {',
    '          _segments.add(_RouteSegment(',
    '            points: points,',
    '            color: Colors.blue,',
    '            width: 4.0,',
    '            isBus: false,',
    '            distance: (props["distance"] as num?)?.toDouble() ?? 0,',
    '            time: (props["time"] as num?)?.toDouble() ?? 0,',
    '          ));',
    '        }',
    '',
    '        _routePoints.addAll(points);',
    '      } else if (type == "Point") {',
    '        final markerType = props["type"] as String? ?? "";',
    '        if (markerType == "start" || markerType == "end" || markerType == "bus_stop") {',
    '          _markers.add(_MapMarker(',
    '            point: LatLng((coords[1] as num).toDouble(), (coords[0] as num).toDouble()),',
    '            type: markerType,',
    '            label: props["label"] as String? ?? "",',
    '            route: props["route"] as String? ?? "",',
    '          ));',
    '        }',
    '      }',
    '    }',
    '',
    '    _routeProperties = geojson["properties"] as Map<String, dynamic>?;',
    '',
    '    if (_routePoints.isNotEmpty) {',
    '      _mapController.fitCamera(CameraFit.bounds(',
    '        bounds: LatLngBounds.fromPoints(_routePoints),',
    '        padding: const EdgeInsets.all(50),',
    '      ));',
    '    }',
    '',
    '    setState(() {',
    '      _isLoading = false;',
    '    });',
    '  }',
    '}',
    '  }',
    ''
]

with open(r"C:\Users\ASUS\Documents\Default Project\frontend\lib\map_page.dart", "r", encoding="utf-8") as f:
    lines = f.readlines()

# Find the class closing brace (line 885, index 884)
insert_idx = 884  # 0-indexed, line 885 is index 884

# Insert all methods
new_lines = lines[:884] + [line + "\n" for line in new_methods] + lines[884:]

with open(r"C:\Users\ASUS\Documents\Default Project\frontend\lib\map_page.dart", "w", encoding="utf-8") as f:
    f.writelines(new_lines)

print("Inserted all helper methods")
print("New line count:", len(lines) + len(new_methods))